Automatically produce generated-configure.sh script
Back-ported from jdk11.

Remove files no longer used; no need to ignore copyright notice
problems in generated-configure.sh.

Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>

diff --git a/common/autoconf/configure b/common/autoconf/configure
--- a/common/autoconf/configure
+++ b/common/autoconf/configure
@@ -21,11 +21,9 @@
 # or visit www.oracle.com if you need additional information or have any
 # questions.
 #
-
 # ===========================================================================
-# (c) Copyright IBM Corp. 2017, 2022 All Rights Reserved
+# (c) Copyright IBM Corp. 2017, 2025 All Rights Reserved
 # ===========================================================================
-#
 
 if test "x$1" != xCHECKME; then
   echo "WARNING: Calling the wrapper script directly is deprecated and unsupported."
@@ -53,72 +51,97 @@ else
   conf_custom_script_dir="$CUSTOM_CONFIG_DIR"
 fi
 
+CURRENT_DIR=`pwd`
+if test "x$CURRENT_DIR" = "x$TOPDIR"; then
+  # We are running configure from the src root.
+  # Create '.configure-support' under $TOPDIR/build.
+  build_support_dir="$TOPDIR/build/.configure-support"
+elif test "x$CURRENT_DIR" = "x$CUSTOM_ROOT"; then
+  # We are running configure from the custom root.
+  # Create '.configure-support' under $CUSTOM_ROOT/build.
+  build_support_dir="$CUSTOM_ROOT/build/.configure-support"
+else
+  # We are running configure from outside of the src dir.
+  # Create 'build_support_dir' in the current directory.
+  build_support_dir="$CURRENT_DIR/configure-support"
+fi
+
+generated_script="$build_support_dir/generated-configure.sh"
+
 ###
-### Test that the generated configure is up-to-date
+### Ensure that the generated configure script is up-to-date.
 ###
 
 run_autogen_or_fail() {
-  if test "x`which autoconf 2> /dev/null`" = x; then
-    echo "Cannot locate autoconf, unable to correct situation."
-    echo "Please install autoconf and run 'bash autogen.sh' to update the generated files."
-    echo "Error: Cannot continue" 1>&2
+  echo "Generating $generated_script"
+
+  AUTOCONF="`which autoconf 2> /dev/null | grep -v '^no autoconf in'`"
+
+  if test "x${AUTOCONF}" = x; then
+    echo "You need autoconf installed to be able to generate the configure script"
+    echo "Error: Cannot find autoconf" 1>&2
     exit 1
+  fi
+
+  autoconf_version=`$AUTOCONF --version | head -1`
+  echo "Using autoconf at ${AUTOCONF} [$autoconf_version]"
+
+  if test "x$CUSTOM_CONFIG_DIR" = "x"; then
+    custom_script_dir="$TOPDIR/jdk/make/closed/autoconf"
   else
-    echo "Running autogen.sh to correct the situation"
-    bash $conf_script_dir/autogen.sh
+    custom_script_dir=$CUSTOM_CONFIG_DIR
+  fi
+
+  custom_hook=$custom_script_dir/custom-hook.m4
+
+  if test -e $custom_hook; then
+    # Generate configure script with custom hooks compiled in.
+    custom_patcher='sed -e "s|#CUSTOM_AUTOCONF_INCLUDE|m4_include([$custom_hook])|"'
+  else
+    custom_patcher='cat'
+  fi
+
+  mkdir -p $build_support_dir
+
+  # Call autoconf but replace the "magic" variable in configure.ac if requested.
+  cat $conf_script_dir/configure.ac | eval $custom_patcher | \
+      ${AUTOCONF} -W all -I$conf_script_dir - > $generated_script
+  rm -rf autom4te.cache
+
+  # Sanity check
+  if test ! -s $generated_script; then
+    echo "Error: Failed to generate runnable configure script" 1>&2
+    rm -f $generated_script
+    exit 1
   fi
 }
 
 check_autoconf_timestamps() {
   for file in $conf_script_dir/configure.ac $conf_script_dir/*.m4 ; do
-    if test $file -nt $conf_script_dir/generated-configure.sh; then
-      echo "Warning: The configure source files is newer than the generated files."
+    if test $file -nt $generated_script; then
+      echo "Runnable configure script is not up to date"
       run_autogen_or_fail
+      return
     fi
   done
 
-  if test -e $conf_custom_script_dir/generated-configure.sh; then
+  if test -d $conf_custom_script_dir; then
     # If custom source configure is available, make sure it is up-to-date as well.
-    for file in $conf_script_dir/configure.ac $conf_script_dir/*.m4 $conf_custom_script_dir/*.m4; do
-      if test $file -nt $conf_custom_script_dir/generated-configure.sh; then
-        echo "Warning: The configure source files is newer than the custom generated files."
+    for file in $conf_custom_script_dir/*.m4; do
+      if test $file -nt $generated_script; then
+        echo "Runnable configure script is not up to date"
         run_autogen_or_fail
+        break
       fi
     done
   fi
 }
 
-check_hg_updates() {
-  if test "x`which hg 2> /dev/null`" != x; then
-    conf_updated_autoconf_files=`cd $conf_script_dir && hg status -mard 2> /dev/null | grep autoconf`
-    if test "x$conf_updated_autoconf_files" != x; then
-      echo "Configure source code has been updated, checking time stamps"
-      check_autoconf_timestamps
-    fi
-
-    if test -e $conf_custom_script_dir; then
-      # If custom source configure is available, make sure it is up-to-date as well.
-      conf_custom_updated_autoconf_files=`cd $conf_custom_script_dir && hg status -mard 2> /dev/null | grep autoconf`
-      if test "x$conf_custom_updated_autoconf_files" != x; then
-        echo "Configure custom source code has been updated, checking time stamps"
-        check_autoconf_timestamps
-      fi
-    fi
-  fi
-}
-
-# Check for local changes
-check_hg_updates
-
-if test -e $conf_custom_script_dir/generated-configure.sh; then
-  # Test if open configure is newer than custom configure, if so, custom needs to
-  # be regenerated. This test is required to ensure consistency with custom source.
-  conf_open_configure_timestamp=`grep DATE_WHEN_GENERATED= $conf_script_dir/generated-configure.sh  | cut -d"=" -f 2`
-  conf_custom_configure_timestamp=`grep DATE_WHEN_GENERATED= $conf_custom_script_dir/generated-configure.sh  | cut -d"=" -f 2`
-  if test $conf_open_configure_timestamp -gt $conf_custom_configure_timestamp; then
-    echo "Warning: The generated configure file contains changes not present in the custom generated file."
-    run_autogen_or_fail
-  fi
+if test -e $generated_script; then
+  check_autoconf_timestamps
+else
+  echo "Runnable configure script is not present"
+  run_autogen_or_fail
 fi
 
 # Autoconf calls the configure script recursively sometimes.
@@ -255,14 +278,8 @@ conf_processed_arguments=("--enable-option-checking=fatal" "${conf_processed_arg
 ###
 ### Call the configure script
 ###
-if test -e $conf_custom_script_dir/generated-configure.sh; then
-  # Custom source configure available; run that instead
-  echo "Running custom generated-configure.sh"
-  conf_script_to_run=$conf_custom_script_dir/generated-configure.sh
-else
-  echo "Running generated-configure.sh"
-  conf_script_to_run=$conf_script_dir/generated-configure.sh
-fi
+echo "Running generated-configure.sh"
+conf_script_to_run=$generated_script
 
 if test "x$conf_debug_configure" != x; then
   # Turn on shell debug output if requested (initial or recursive)
